theme: minima

name: howtos

title: howtos

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      date: "2029-02-23T10:20:00Z" # This field cannot be empty

# minima:
#   date_format: "%b %-d, %Y"

# generate social links in footer
# social_links:
#   twitter: wgilpin0
#   github:  williamgilpin


# Empty header pages
header_pages:
  -



# Base URL of the published website
# baseurl: http://www.wgilpin.com/howto/index.html
# url: http://www.wgilpin.com